image: gcc
before_script:
  - JOBS=$(expr $(nproc) + 1)
  - apt-get update
  - apt-get install -y libsctp-dev

build:
  stage: build

  script:
    - mkdir build
    - cd build
    - ../configure
    - make -j${JOBS}

  artifacts:
    paths:
      - build

build-static:
  stage: build

  script:
    - mkdir build-static
    - cd build-static
    - ../configure --enable-static --disable-shared
    - make -j${JOBS}

  artifacts:
    paths:
      - build
      - build-static

test-build:
  stage: test
  needs: ["build"]

  script:
    - cd build
    - openssl genrsa -out src/private.pem 2048
    - openssl rsa -in src/private.pem -outform PEM -pubout -out src/public.pem
    - make check

test-build-static:
  stage: test
  needs: ["build-static"]

  script:
    - cd build-static
    - openssl genrsa -out src/private.pem 2048
    - openssl rsa -in src/private.pem -outform PEM -pubout -out src/public.pem
    - make check

test-tcp-localhost:
  stage: test
  needs: ["build"]


  script:
    - cd build
    - ./src/iperf3 -s -D
    - ./src/iperf3 -V -c localhost

test-tcp-localhost-static:
  stage: test
  needs: ["build-static"]

  script:
    - cd build-static
    - ./src/iperf3 -s -D
    - ./src/iperf3 -V -c localhost

test-udp-localhost:
  stage: test
  needs: ["build"]

  script:
    - cd build
    - ./src/iperf3 -s -D
    - ./src/iperf3 -V -u -c localhost

test-udp-localhost-static:
  stage: test
  needs: ["build-static"]

  script:
    - cd build-static
    - ./src/iperf3 -s -D
    - ./src/iperf3 -V -u -c localhost

test-sctp-localhost:
  stage: test
  needs: ["build"]
  allow_failure: true

  script:
    - cd build
    - ./src/iperf3 -s -D
    - ./src/iperf3 -V --sctp -c localhost

test-sctp-localhost-static:
  stage: test
  needs: ["build-static"]
  allow_failure: true

  script:
    - cd build-static
    - ./src/iperf3 -s -D
    - ./src/iperf3 -V --sctp -c localhost

test-vsock-localhost:
  stage: test
  needs: ["build"]
  allow_failure: true

  script:
    - cd build
    - ./src/iperf3 --vsock -s -D
    - ./src/iperf3 -V --vsock -c 1

test-vsock-localhost-static:
  stage: test
  needs: ["build-static"]
  allow_failure: true

  script:
    - cd build-static
    - ./src/iperf3 --vsock -s -D
    - ./src/iperf3 -V --vsock -c 1
